### ISSUE TITLE
TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by zeke** [jsoma/tabletop#154]
I tried out https://spreadsheet.glitch.me/ and it's failing. I [remixed the app](https://glitch.com/edit/#!/hurricane-flare?path=server.js:16:52) to figure out what's failing and I see this in the logs:

```
/app/node_modules/tabletop/src/tabletop.js:327
1:43 PM

      this.googleSheetName = data.feed.title.$t;
1:43 PM

                                      ^
1:43 PM

1:43 PM

TypeError: Cannot read property 'title' of undefined
1:43 PM

    at Object.loadSheets (/app/node_modules/tabletop/src/tabletop.js:327:39)
1:43 PM

    at Request._callback (/app/node_modules/tabletop/src/tabletop.js:269:18)
1:43 PM

    at Request.self.callback (/app/node_modules/request/request.js:188:22)
1:43 PM

    at emitTwo (events.js:106:13)
1:43 PM

    at Request.emit (events.js:191:7)
1:43 PM

    at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
1:43 PM

    at emitOne (events.js:96:13)
1:43 PM

    at Request.emit (events.js:188:7)
1:43 PM

    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
1:43 PM

    at IncomingMessage.g (events.js:291:16)
```

Seems related to #104

**Comment by flushentitypacket** [comment]
I ran into this error as well.

Turns out there is a bit in the README about how to troubleshoot it:

https://github.com/jsoma/tabletop#1-publishing-your-google-sheet

The URL should not have a `/d/e` in it.

**Comment by noudadrichem** [comment]
But what is the fix for this? Removing /e/ breaks the whole thing. Can't get it to work...

**Comment by zeke** [comment]
cc @jsoma

**Comment by noudadrichem** [comment]
My fix was to use the Sheet code instead of using the 'published to web' URI code.

**Comment by jsoma** [comment]
Yup, as mentioned in the link above you can no longer use the "Publish to web" code (unless you've got a old spreadsheet)
