### ISSUE TITLE
Tabletop.Model.fetchPrettyColumns causes endless loop when using newest Flatware proxy

### ISSUE THREAD

**Issue by benbreedlove** [jsoma/tabletop#80]
What it says on the tin.

**Comment by aendrew** [comment]
I've noticed that too, possibly has to do with the PR I did awhile back. Will take a look on Wednesday when I'm back at work.

**Comment by danswick** [comment]
Just ran into the same issue. Passing option `prettyColumnNames: false` fixes the loop error, but obviously breaks functions relying on specific column names.

**Comment by aendrew** [comment]
Apologies for the huge delay in getting back to this; I'll be doing some stuff with Flatware this weekend and will try to take a look.

**Comment by danswick** [comment]
@aendrew - it looks like the latest version of flatware does not sync using pretty column names (the data saved on AWS has underscores stripped and all column names set to lowercase). Could this have something to do with the issue? It also seems that `fetchPrettyColumns` is never actually calling `loadPrettyColumns`. Could it be that `requestData()` is not handing off the proper object to the callback function? 

Please excuse me if these are obvious questions and thanks for looking into this!

**Comment by aendrew** [comment]
@danswick Could very well be. TBH, it seems like an issue more with Sheets than anything; all my change did was tell the app to try the updated Sheets path based on env var. Have you tried setting `FLATWARE_USE_OLD_SHEETS=true`?

**Comment by danswick** [comment]
@aendrew Just gave that a shot with no luck. Still getting non-pretty column names and the endless loop. 

Regular old tabletop is working fine, including properly formatted column names, but column names are 'de-prettified' once they go through flatware. 

Thanks again!

**Comment by aendrew** [comment]
Just tried a brand-new install of Flatware using 1.4.0 — confirming `prettyColumns` is totally broken. I've never really used that option, so not sure how to fix it; I retract what I said earlier, seems more like an issue with Tabletop itself.

**Comment by aendrew** [comment]
Trying to replicate the issue in the Node REPL, I get the following error:
```> TypeError: Cannot read property 'entry' of undefined
    at Object.Tabletop.loadSheets (/Users/aendrew/Sites/tabletop/src/tabletop.js:308:34)
    at Request._callback (/Users/aendrew/Sites/tabletop/src/tabletop.js:248:18)
    at Request.self.callback (/Users/aendrew/Sites/tabletop/node_modules/request/index.js:142:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/aendrew/Sites/tabletop/node_modules/request/index.js:856:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/aendrew/Sites/tabletop/node_modules/request/index.js:808:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)```

**Comment by aendrew** [comment]
I get the following error when I try to replicate the issue via the NodeJS REPL:
```
TypeError: Cannot read property 'entry' of undefined
    at Object.Tabletop.loadSheets (/Users/aendrew/Sites/tabletop/src/tabletop.js:308:34)
    at Request._callback (/Users/aendrew/Sites/tabletop/src/tabletop.js:248:18)
    at Request.self.callback (/Users/aendrew/Sites/tabletop/node_modules/request/index.js:142:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/aendrew/Sites/tabletop/node_modules/request/index.js:856:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/aendrew/Sites/tabletop/node_modules/request/index.js:808:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

**Comment by aendrew** [comment]
@all — please see the above issue on Flatware. According to the Tabletop readme, an extra request is necessary to get the pretty column names, and I'm pretty sure that Flatware doesn't do that yet.

**Comment by danswick** [comment]
Oh wow, thanks for digging so deep into this, @aendrew. Your diagnosis makes perfect sense.

**Comment by jsoma** [comment]
Thanks times a million for all of that @aendrew! I'm taking a look now, hopefully we can get this all sorted out.

**Comment by jsoma** [comment]
As of this brand-new moment, `prettyColumnNames` will default to `false` if you're using a proxy (although you can override it). While we were at it, I also updated Flatware to use TLS instead of SSLv3, which Amazon has deprecated, so you might want to update even if you're passing in `false`.

**Comment by aendrew** [comment]
Good to know! Thanks for the new release!
